// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvVwRR5N-eNuIpWYtlqfxtTViiGB8H9ZQ',
    appId: '1:279326220201:web:38d6e56f573880670f2eb8',
    messagingSenderId: '279326220201',
    projectId: 'machine06',
    authDomain: 'machine06.firebaseapp.com',
    storageBucket: 'machine06.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4OHSkSEKNZEZy3tCYX7AH3KtBRV0jHmA',
    appId: '1:279326220201:android:6edacdb706e355e40f2eb8',
    messagingSenderId: '279326220201',
    projectId: 'machine06',
    storageBucket: 'machine06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeqGVS1NK8uQglRkhp4BFrbkvSdDduZgw',
    appId: '1:279326220201:ios:4da60c0b9ab6a1a30f2eb8',
    messagingSenderId: '279326220201',
    projectId: 'machine06',
    storageBucket: 'machine06.appspot.com',
    iosBundleId: 'com.example.machine06',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeqGVS1NK8uQglRkhp4BFrbkvSdDduZgw',
    appId: '1:279326220201:ios:4da60c0b9ab6a1a30f2eb8',
    messagingSenderId: '279326220201',
    projectId: 'machine06',
    storageBucket: 'machine06.appspot.com',
    iosBundleId: 'com.example.machine06',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvVwRR5N-eNuIpWYtlqfxtTViiGB8H9ZQ',
    appId: '1:279326220201:web:bf4c859a53d8bfa70f2eb8',
    messagingSenderId: '279326220201',
    projectId: 'machine06',
    authDomain: 'machine06.firebaseapp.com',
    storageBucket: 'machine06.appspot.com',
  );
}
